# Generated by Django 5.1.1 on 2025-02-13 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0003_migrate_video_rating'),
        ('youtube_integration', '0006_alter_video_dislike_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videointeraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='videointeraction',
            unique_together={('user', 'video')},
        ),
    ]
