# Generated by Django 5.1.1 on 2024-09-30 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='Unknown', null=True),
        ),
    ]
