# Generated by Django 5.1.1 on 2024-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0002_video_category_video_created_at_video_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
