# Generated by Django 5.1.1 on 2024-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0003_youtubecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
