# Generated by Django 5.1.1 on 2024-11-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0004_video_dislike_count_video_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
