# Generated by Django 5.1.1 on 2025-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0005_video_channel_title_video_language_video_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
    ]
