# Generated by Django 5.1.1 on 2025-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0006_alter_video_dislike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
