# Generated by Django 5.1.1 on 2025-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_integration', '0007_video_playlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
