# Generated by Django 5.1.1 on 2025-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistvideo',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
