# Generated by Django 5.1.1 on 2025-02-21 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlistvideo_ordem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recomendacao', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
                ('recomendado_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('recomendado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
