# Generated by Django 5.1.1 on 2025-02-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlistrecomendacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='nivel_acesso',
            field=models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='privada', max_length=10),
        ),
    ]
