# Generated by Django 5.1.1 on 2025-02-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videorating_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoRating',
        ),
    ]
