# Generated by Django 5.1.1 on 2024-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='duracao_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linguagem_preferida',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
