# Generated by Django 5.1.1 on 2024-11-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_duracao_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linguagem_preferida',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aplicar_filtros',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linguagens_preferidas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
