# Generated by Django 5.1.1 on 2025-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_linguagem_preferida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='duracao_maxima',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duracao_faixa',
            field=models.CharField(blank=True, choices=[('short', 'Curtos (até 2 minutos)'), ('medium', 'Normais (até 15 minutos)'), ('long', 'Longos (mais de 20 minutos)')], max_length=10, null=True),
        ),
    ]
