# Generated by Django 5.1.1 on 2025-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_duracao_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='duracao_faixa',
            field=models.CharField(blank=True, choices=[('short', 'Curtos (até 2 minutos)'), ('medium', 'Normais (até 15 minutos)'), ('long', 'Longos (mais de 15 minutos)'), ('none', 'Sem limite de tempo')], max_length=10, null=True),
        ),
    ]
