# Generated by Django 5.1.1 on 2025-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_duracao_faixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor')], default='student', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='duracao_faixa',
            field=models.CharField(choices=[('short', 'Curtos (até 2 minutos)'), ('medium', 'Normais (até 15 minutos)'), ('long', 'Longos (mais de 15 minutos)'), ('none', 'Sem limite de tempo')], default='none', max_length=10),
        ),
    ]
