# Generated by Django 5.1.1 on 2025-02-21 14:59

import recomendador_videos.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_avatar_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=recomendador_videos.accounts.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor')], default='student', max_length=10),
        ),
    ]
